### ISSUE TITLE
 error: languages.h: No such file or directory

### ISSUE THREAD

**Issue by shuvo12348635** [willmendil/ESPBug#1]
#include "languages.h"

                       ^

compilation terminated.

exit status 1
languages.h: No such file or directory

how can i solve it ..
please help to solve it

**Comment by akshayaruku** [comment]
i am also getting same error .Please help me

**Comment by zazman** [comment]
Same here...

**Comment by evloebenstein** [comment]
same

**Comment by willmendil** [comment]
The restructuring of the project should solve this, at least it did not crash on my vm
