### ISSUE TITLE
Web interface for victim is in French

### ISSUE THREAD

**Issue by UdanthaP** [willmendil/ESPBug#14]
Web interface for victim is in French. Please find a way to fix this.

**Comment by willmendil** [comment]
All you need to do is translate the text in the web_pages folder and use the updated documentation to help you convert the new project (make note that what is converted is what is inside web_converter, you'll need to manually move them to the espbug/web_pages folder)

https://github.com/willmendil/ESPBug#convert-webpages

**Comment by UdanthaP** [comment]
Thanks for the information!
