### ISSUE TITLE
Need a wifi password required page.

### ISSUE THREAD

**Issue by aponfurious** [willmendil/ESPBug#18]
can any one give me a wifi password required page! And make the page into English language.

**Comment by willmendil** [comment]
what do you mean?
you can make your own pages and convert them to hex to compile with the program

**Comment by aponfurious** [comment]
Many people including me doesn’t know how to use webconvertor.py!  can you please make a video how use webconvertor.py. !! I think that video solve many problems! thank you.

**Comment by willmendil** [comment]
Ok ok, you know how to talk yourself into what you want, I'll do a video, just give me a bit of time, I'll make it this week
