### ISSUE TITLE
Webconverter use issue! 

### ISSUE THREAD

**Issue by aponfurious** [willmendil/ESPBug#19]
Definitely its a great project! But many of us including me don't know how to use webconverter.py . Need a video tutorial on webconverter.py . Thank you in advanced.  I think you will make a video on it. because espbug is hero.

**Comment by willmendil** [comment]
Ok ok, you know how to talk yourself into what you want, I'll do a video, just give me a bit of time, I'll make it this week

**Comment by willmendil** [comment]
https://youtu.be/1cIXfD_Jz5s   it's being encoded, but should be published soon (fyi: quick and dirty)
