### ISSUE TITLE
ESP8266WebServer has no member named 'authenticate'

### ISSUE THREAD

**Issue by taciturnsays** [willmendil/ESPBug#3]
Hello, im having an error trying to compile after i include the ftps server library from the link on the project that says the following:
'class ESP8266WebServer' has no member named 'authenticate'

Any thing else i need to add or change?

**Comment by willmendil** [comment]
FTP was a thing i wanted to program in so to be able to retreive logs easily, but so far it's not programmed in. Don't know if I'm going to do it
