### ISSUE TITLE
Facebook page request (language: english)

### ISSUE THREAD

**Issue by merajalishah** [willmendil/ESPBug#4]

**Comment by taciturnsays** [comment]
Why the facebook page? The developer doesnt even reply here, it looks like this project has been abandoned...

**Comment by willmendil** [comment]
not really abandoned, just away for a whilst. I don't feel comfortable copying these pages, i already cloned the google login. I'd invite you to make your own, maybe make a pull requets here without the logos if you want. Won't be able to review them till i get home in a few months and could test them though
