### ISSUE TITLE
Updating portal html files and recompile then ? nothing change !

### ISSUE THREAD

**Issue by ihisoka** [willmendil/ESPBug#9]

**Comment by willmendil** [comment]
need more information on your question mate, I don't understand what you mean

**Comment by johnis23** [comment]
i have an issue that is about the portal html file. I change it from .../webpages/compressed/captive.html. The captive.html is from the extraction of the captive.html.gz. I mod the html file (page), i upload again the firmware because of the change i did and it didnt work...
